# various constants used throughout the project 
FIELD_WIDTH_M = 24.0
FIELD_HEIGHT_M = 14.0
PLAYER_RADIUS_M = 0.5
BALL_RADIUS_M = 0.4
SERVER_TICK_HZ = 60
SNAPSHOT_HZ = 20
PLAYER_ACCEL_MPS2 = 10.0
FRICTION = 0.85
GOAL_OPENING_M = 2.5
